# Generated by Django 3.0.8 on 2020-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_http_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='yelp_business_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
