# Generated by Django 3.0.8 on 2020-07-26 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_auto_20200719_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='user_info',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='http_ref',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='place',
            name='tags',
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.CharField(default='food', max_length=1000),
            preserve_default=False,
        ),
    ]
