# Generated by Django 3.0.8 on 2020-07-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20200726_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='yelp_business_id',
            field=models.CharField(max_length=30),
        ),
    ]
