# Generated by Django 3.0.8 on 2020-07-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200727_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
